name: ci
on:
  push:
    branches: [ main, release ]
  pull_request:
    branches: [ main, release ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"
  RUSTDOCFLAGS: "-Dwarnings"  

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: true
    env:
      STAGE: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup Rust
        run: rustup update

      - name: build Cache
        id: build-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target
          key: build-cache-${{ runner.os }}-${{ github.workflow }}-${{ hashFiles('**.toml', '**.lock') }}-${{ github.ref }}
          
      - name: build
        run: |
          cd rust
          cargo build --all-targets --all-features
          cargo build --release --all-targets --all-features

      - name: fmt check
        run: |
          cd rust
          cargo fmt --all -- --check

      - name: check
        run: |
          cd rust
          cargo check --all

      - name: tests
        run: |
          cd rust
          cargo test --release --all --all-features

      - name: doc
        run: |
          cd rust
          cargo doc --workspace --all-features --no-deps
